// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIq5dw2hjXu9gJ-98vej-RIXosJ_w3nOU',
    appId: '1:759545418723:web:c40a59f84180d88fae46d6',
    messagingSenderId: '759545418723',
    projectId: 'vertex-login',
    authDomain: 'vertex-login.firebaseapp.com',
    storageBucket: 'vertex-login.appspot.com',
    measurementId: 'G-D43DTZ8T81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-qthBUeoj6Nr9GU7frhUC9nFYvwhImOc',
    appId: '1:759545418723:android:1ec9bac37a7328d5ae46d6',
    messagingSenderId: '759545418723',
    projectId: 'vertex-login',
    storageBucket: 'vertex-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC23jY6e-Tyr35QQsHD4yR2q_vC-FTowcs',
    appId: '1:759545418723:ios:7e83d48fc68e493fae46d6',
    messagingSenderId: '759545418723',
    projectId: 'vertex-login',
    storageBucket: 'vertex-login.appspot.com',
    iosClientId: '759545418723-h89599lf3f6gm1lvmu1ff78o05mhicn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.vertex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC23jY6e-Tyr35QQsHD4yR2q_vC-FTowcs',
    appId: '1:759545418723:ios:7e83d48fc68e493fae46d6',
    messagingSenderId: '759545418723',
    projectId: 'vertex-login',
    storageBucket: 'vertex-login.appspot.com',
    iosClientId: '759545418723-h89599lf3f6gm1lvmu1ff78o05mhicn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.vertex',
  );
}
